-- Run this after applying the identity-column migration on any server.
-- It finds every GENERATED BY DEFAULT AS IDENTITY column in the public schema
-- and sets the backing sequence to max(id) + 1, so existing rows don't conflict
-- with new inserts.

DO $$
DECLARE
    r RECORD;
    max_id bigint;
    seq_name text;
    full_table_name text;
BEGIN
    FOR r IN
        SELECT c.table_schema,
               c.table_name,
               c.column_name
        FROM information_schema.columns c
        JOIN information_schema.tables t
            ON t.table_schema = c.table_schema
           AND t.table_name = c.table_name
        WHERE c.table_schema = 'public'
          AND c.is_identity = 'YES'
          AND t.table_type = 'BASE TABLE'
        ORDER BY c.table_schema, c.table_name
    LOOP
        full_table_name := quote_ident(r.table_schema) || '.' || quote_ident(r.table_name);
        seq_name := pg_get_serial_sequence(full_table_name, r.column_name);

        IF seq_name IS NOT NULL THEN
            EXECUTE format('SELECT COALESCE(MAX(%I), 0) FROM %s', r.column_name, full_table_name)
                INTO max_id;

            PERFORM setval(seq_name, max_id + 1, false);

            RAISE NOTICE 'Set % to % (max % in %.%=%)',
                seq_name, max_id + 1, max_id, r.table_schema, r.table_name, r.column_name;
        ELSE
            RAISE NOTICE 'No sequence found for %.%', full_table_name, r.column_name;
        END IF;
    END LOOP;
END $$;
