parameters:

    cohortg.sitename: cohortg
    cohortg.uploadpath:


twig:
    globals:
        cohortg_sitename: '%cohortg.sitename%'


services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    cohortg_authentication_handler:
        class: App\CohortgBundle\Security\Authentication\CohortgLoginSuccessHandler

    cohortg_role_voter:
        class: App\CohortgBundle\Security\Voter\CohortgRoleVoter
        public: false
        tags:
            - { name: security.voter }

    cohortg_permission_voter:
        class: App\CohortgBundle\Security\Voter\CohortgPermissionVoter
        public: false
        tags:
            - { name: security.voter }
