services:

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    App\UtilBundles\FOSCommentBundle\Util\:
        resource: '%kernel.project_dir%/src/App/UtilBundles/FOSCommentBundle/Util'
#        resource: '../../../../../../src/App/UtilBundles/FOSCommentBundle/Util'


    user_comment_utility:
        class: App\UtilBundles\FOSCommentBundle\Util\UserCommentUtil
#        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    user_comment_listener_utility:
        class: App\UtilBundles\FOSCommentBundle\Util\FosCommentListenerUtil
#        arguments: ["@doctrine.orm.entity_manager", "@service_container"]


