<?php

namespace Proxies\__CG__\Oleg\OrderformBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Patient extends \Oleg\OrderformBundle\Entity\Patient implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setMrn($mrn)
    {
        $this->__load();
        return parent::setMrn($mrn);
    }

    public function getMrn()
    {
        $this->__load();
        return parent::getMrn();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setAge($age)
    {
        $this->__load();
        return parent::setAge($age);
    }

    public function getAge()
    {
        $this->__load();
        return parent::getAge();
    }

    public function setSex($sex)
    {
        $this->__load();
        return parent::setSex($sex);
    }

    public function getSex()
    {
        $this->__load();
        return parent::getSex();
    }

    public function setDob($dob)
    {
        $this->__load();
        return parent::setDob($dob);
    }

    public function getDob()
    {
        $this->__load();
        return parent::getDob();
    }

    public function setClinicalHistory($clinicalHistory)
    {
        $this->__load();
        return parent::setClinicalHistory($clinicalHistory);
    }

    public function getClinicalHistory()
    {
        $this->__load();
        return parent::getClinicalHistory();
    }

    public function addSpecimen(\Oleg\OrderformBundle\Entity\Specimen $specimen)
    {
        $this->__load();
        return parent::addSpecimen($specimen);
    }

    public function addSpeciman(\Oleg\OrderformBundle\Entity\Specimen $specimen)
    {
        $this->__load();
        return parent::addSpeciman($specimen);
    }

    public function removeSpecimen(\Oleg\OrderformBundle\Entity\Specimen $specimen)
    {
        $this->__load();
        return parent::removeSpecimen($specimen);
    }

    public function removeSpeciman(\Oleg\OrderformBundle\Entity\Specimen $specimen)
    {
        $this->__load();
        return parent::removeSpeciman($specimen);
    }

    public function getSpecimen()
    {
        $this->__load();
        return parent::getSpecimen();
    }

    public function setSpecimen(\Doctrine\Common\Collections\ArrayCollection $specimen)
    {
        $this->__load();
        return parent::setSpecimen($specimen);
    }

    public function addOrderinfo(\Oleg\OrderformBundle\Entity\OrderInfo $orderinfo)
    {
        $this->__load();
        return parent::addOrderinfo($orderinfo);
    }

    public function removeOrderinfo(\Oleg\OrderformBundle\Entity\OrderInfo $orderinfo)
    {
        $this->__load();
        return parent::removeOrderinfo($orderinfo);
    }

    public function getOrderinfo()
    {
        $this->__load();
        return parent::getOrderinfo();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'mrn', 'name', 'age', 'sex', 'dob', 'clinicalHistory', 'orderinfo', 'specimen');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}