#doctrine:
#    dbal:
#        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'

        # only needed for MySQL
#        charset: utf8mb4
#        default_table_options:
#            collate: utf8mb4_unicode_ci
#    orm:
#        auto_generate_proxy_classes: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#        auto_mapping: true
#        mappings:
#            App:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App

#with doctrine/orm 3.0, annotations will no longer be supported
#https://github.com/rectorphp/rector
#https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#annotationtoattributerector
#https://getrector.com/blog/how-to-upgrade-annotations-to-attributes

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                #wrapper_class: App\Routing\DBAL\MultiDbConnectionWrapper
                driver:   '%database_driver%'
                host:     '%database_host%'
                port:     '%database_port%'
                dbname:   '%database_name%'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8
                # if using pdo_sqlite as your database driver, add the path in parameters.yml
                # e.g. database_path: %kernel.root_dir%/data/data.db3
                # path:     %database_path%
            external:
                driver:   '%database_driver_external%'
                host:     '%database_host_external%'
                port:     '%database_port_external%'
                dbname:   '%database_name_external%'
                user:     '%database_user_external%'
                password: '%database_password_external%'
                charset:  UTF8
            #system DB which will be used for multitenancy
            systemdb:
                driver:   '%database_driver_systemdb%'
                host:     '%database_host_systemdb%'
                port:     '%database_port_systemdb%'
                dbname:   '%database_name_systemdb%'
                user:     '%database_user_systemdb%'
                password: '%database_password_systemdb%'
                charset:  UTF8
    orm:
        #auto_generate_proxy_classes: '%kernel.debug%'
        #https://stackoverflow.com/questions/12894822/access-denied-error-on-rename-call-when-uploading-files-in-symfony
        #Warning: rename cache Proxies Access is denied (code: 5): set auto_generate_proxy_classes: false
        auto_generate_proxy_classes: false
        enable_lazy_ghost_objects: true
#        auto_mapping: true
        default_entity_manager: default
        entity_managers:
            default:
#                auto_mapping: true
#                metadata_cache_driver: ~
#                    type: service
#                    id: doctrine.system_cache_provider
                result_cache_driver: ~
                query_cache_driver: ~
                connection: default
                mappings:
                    App\OrderformBundle:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/App/OrderformBundle/Entity'
                        prefix: 'App\OrderformBundle\Entity'
                        alias: 'AppOrderformBundle'
                    App\UserdirectoryBundle:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/App/UserdirectoryBundle/Entity'
                        prefix: 'App\UserdirectoryBundle\Entity'
                        alias: 'AppUserdirectoryBundle'
                    App\FellAppBundle:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/App/FellAppBundle/Entity'
                        prefix: 'App\FellAppBundle\Entity'
                        alias: 'AppFellAppBundle'
                    App\ResAppBundle:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/App/ResAppBundle/Entity'
                        prefix: 'App\ResAppBundle\Entity'
                        alias: 'AppResAppBundle'
                    App\DeidentifierBundle:
                        is_bundle: false
                        #type: annotation
                        type: attribute
                        dir: '%kernel.project_dir%/src/App/DeidentifierBundle/Entity'
                        prefix: 'App\DeidentifierBundle\Entity'
                        alias: 'AppDeidentifierBundle'
                    App\VacReqBundle:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/App/VacReqBundle/Entity'
                        prefix: 'App\VacReqBundle\Entity'
                        alias: 'AppVacReqBundle'
                    App\CallLogBundle:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/App/CallLogBundle/Entity'
                        prefix: 'App\CallLogBundle\Entity'
                        alias: 'AppCallLogBundle'
                    App\CrnBundle:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/App/CrnBundle/Entity'
                        prefix: 'App\CrnBundle\Entity'
                        alias: 'AppCrnBundle'
                    App\TranslationalResearchBundle:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/App/TranslationalResearchBundle/Entity'
                        prefix: 'App\TranslationalResearchBundle\Entity'
                        alias: 'AppTranslationalResearchBundle'
                    App\DashboardBundle:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/App/DashboardBundle/Entity'
                        prefix: 'App\DashboardBundle\Entity'
                        alias: 'AppDashboardBundle'
#                    AppOrderformBundle: ~
#                    AppUserdirectoryBundle: ~
#                    AppFellAppBundle: ~
#                    AppDeidentifierBundle: ~
#                    AppVacReqBundle: ~
#                    AppCallLogBundle: ~
#                    AppTranslationalResearchBundle: ~
#                    FOSCommentBundle: ~
                    gedmo_tree:
                        #type: annotation
                        type: attribute
                        prefix: Gedmo\Tree\Entity
#                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                #hydrators:
                #     SimpleHydrator: \App\UserdirectoryBundle\Hydrator\SimpleHydrator
                #     StainHydrator: \App\OrderformBundle\Hydrator\StainHydrator
                dql:
                     string_functions:
                        CAST: App\UserdirectoryBundle\Query\CastFunction
                        #GROUP_CONCAT: App\UserdirectoryBundle\Query\GroupConcat
                     datetime_functions:
                        #date: DoctrineExtensions\Query\Mysql\Date
                        YEAR: DoctrineExtensions\Query\Postgresql\Year
            external:
                connection: external

            systemdb:
                connection: systemdb


#when@test:
#    doctrine:
#        dbal:
#            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

