#To debug firewall:
#https://lindevs.com/get-configured-firewalls-using-console-command-in-symfony
#php bin/console debug:firewall
#php bin/console debug:firewall ldap_employees_firewall

security:

    firewalls:

        #{tenantprefix}/ %tenantprefix%
        #this firewall name must be the same as in the bundle's service.yml.
        external_ldap_firewall:
            #pattern: ^/(%multilocales%)(%locdel%)scan
            #pattern: ^/scan
            pattern: ^.*/scan
            context: scan_auth
            switch_user: true
            custom_authenticators:
                  authenticator: custom_guard_authenticator
            form_login:
                # "login" is the name of the route created previously
                login_path: scan_login
                check_path: scan_login_check
            logout:
                path:   scan_logout
                target: scan_login
                #invalidate_session: false
            lazy: true
            provider: users
            access_denied_url: scan_access_request_new_plain #/scan/access-requests/new/create  #/scan/scan-order/no-permission
            remember_me:
                secret:      "%secret%"
                lifetime: 28800 # 8 hours in seconds
                #path:     /(%multilocales%)(%locdel%)scan
                #path:     /scan
#                always_remember_me: true

        #pattern: ^/(%multilocales%)(%locdel%)directory has a problem when 'default' string is hidden in url.
        #Therefore, pattern: ^.*/directory is safer

        ldap_employees_firewall:
              #pattern: ^.*/%tenantprefix%/directory //^.* will make patern can be c/wcm/pathology/directory or c/lmh/pathology/directory
              #pattern: ^/(%multilocales%)(%locdel%)directory
              pattern: ^.*/directory #^.*/directory will support empty default prefix (/directory) and multi-tenancy (/system/directory)
              #pattern: ^/(system|default)/directory
              context: scan_auth
              switch_user: true
              custom_authenticators:
                  authenticator: custom_guard_authenticator
              #working version
              form_login:
                  login_path: employees_login #/%tenantprefix%directory/login
                  check_path: employees_login_check #employees_login_check #/%tenantprefix%directory/login
                  enable_csrf: true
              #TODO: check_path does not redirect to my custom controller?
              #form_login:
              #    login_path: employees_login
              #    check_path: login_check #/directory/login_check2
                  #form_only: true
#              form_login:
#                  login_path: employees_login
#                  check_path: pre_security_login
#                  form_only: false
#                  post_only: false
#                  enable_csrf: true
              logout:
                  path:   logout #/%tenantprefix%directory/logout
                  target: login #/%tenantprefix%directory/login
                  #invalidate_session: false
              lazy: true
              provider: users
              access_denied_url: employees_access_request_new_plain #/%tenantprefix%directory/access-requests/new/create
              #access_denied_url: /directory/access-requests/new/create
              remember_me:
                  secret:      "%secret%"
                  lifetime: 28800 # 8 hours in seconds
              #    path:     /(%multilocales%)(%locdel%)directory
#                  #path:     /directory

        ldap_fellapp_firewall:
            #pattern: ^/(%multilocales%)(%locdel%)fellowship-applications
            pattern: ^.*/fellowship-applications
            context: scan_auth
            switch_user: true
            custom_authenticators:
                authenticator: custom_guard_authenticator
            form_login:
                login_path: fellapp_login
                check_path: fellapp_login_check
            logout:
                path:   fellapp_logout
                target: fellapp_login
                #invalidate_session: false
            #anonymous:  true
            lazy: true
            provider: users
            access_denied_url: fellapp_access_request_new_plain #/fellowship-applications/access-requests/new/create
            remember_me:
                secret:      "%secret%"
                lifetime: 28800 # 8 hours in seconds
                #path:     /(%multilocales%)(%locdel%)fellowship-applications
                #path:     /fellowship-applications
#                always_remember_me: true

        ldap_resapp_firewall:
            #pattern: ^/(%multilocales%)(%locdel%)residency-applications
            pattern: ^.*/residency-applications
            context: scan_auth
            switch_user: true
            custom_authenticators:
                authenticator: custom_guard_authenticator
            form_login:
                login_path: resapp_login
                check_path: resapp_login_check
            logout:
                path:   resapp_logout
                target: resapp_login
                #invalidate_session: false
            lazy: true
            provider: users
            access_denied_url: resapp_access_request_new_plain #/residency-applications/access-requests/new/create
            remember_me:
                secret:      "%secret%"
                lifetime: 28800 # 8 hours in seconds
                #path:     /(%multilocales%)(%locdel%)residency-applications
                #path:     /residency-applications

        ldap_deidentifier_firewall:
            #pattern: ^/(%multilocales%)(%locdel%)deidentifier
            pattern: ^.*/deidentifier
            context: scan_auth
            switch_user: true
            custom_authenticators:
                authenticator: custom_guard_authenticator
            form_login:
                login_path: deidentifier_login
                check_path: deidentifier_login_check
            logout:
                path:   deidentifier_logout
                target: deidentifier_login
                #invalidate_session: false
            lazy: true
            provider: users
            access_denied_url: deidentifier_access_request_new_plain #/deidentifier/access-requests/new/create
            remember_me:
                secret:      '%secret%'
                lifetime: 28800 # 8 hours in seconds
                #path:     /(%multilocales%)(%locdel%)deidentifier
                #path:     /deidentifier
#                always_remember_me: true

        ldap_vacreq_firewall:
            #pattern: ^/(%multilocales%)(%locdel%)time-away-request
            pattern: ^.*/time-away-request
            context: scan_auth
            switch_user: true
            custom_authenticators:
                authenticator: custom_guard_authenticator
            form_login:
                login_path: vacreq_login
                check_path: vacreq_login_check
            logout:
                path:   vacreq_logout
                target: vacreq_login
                #invalidate_session: false
            lazy: true
            provider: users
            access_denied_url: vacreq_access_request_new_plain #/time-away-request/access-requests/new/create
            remember_me:
                secret:      "%secret%"
                lifetime: 28800 # 8 hours in seconds
                #path:     /(%multilocales%)(%locdel%)time-away-request
                #path:     /time-away-request
#                always_remember_me: true

        ldap_calllog_firewall:
            #pattern: ^/(%multilocales%)(%locdel%)call-log-book
            pattern: ^.*/call-log-book
            context: scan_auth
            switch_user: true
            custom_authenticators:
                authenticator: custom_guard_authenticator
            form_login:
                login_path: calllog_login
                check_path: calllog_login_check
            logout:
                path:   calllog_logout
                target: calllog_login
                #invalidate_session: false
            lazy: true
            provider: users
            access_denied_url: calllog_access_request_new_plain #/call-log-book/access-requests/new/create
            remember_me:
                secret:      "%secret%"
                lifetime: 28800 # 8 hours in seconds
                #path:     /(%multilocales%)(%locdel%)call-log-book
                #path:     /call-log-book
#                always_remember_me: true

        ldap_crn_firewall:
            #pattern: ^/(%multilocales%)(%locdel%)critical-result-notifications
            pattern: ^.*/critical-result-notifications
            context: scan_auth
            switch_user: true
            custom_authenticators:
                authenticator: custom_guard_authenticator
            form_login:
                login_path: crn_login
                check_path: crn_login_check
            logout:
                path:   crn_logout
                target: crn_login
                #invalidate_session: false
            lazy: true
            provider: users
            access_denied_url: crn_access_request_new_plain #/critical-result-notifications/access-requests/new/create
            remember_me:
                secret:      "%secret%"
                lifetime: 28800 # 8 hours in seconds
                #path:     /(%multilocales%)(%locdel%)critical-result-notifications
                #path:     /critical-result-notifications

        ldap_translationalresearch_firewall:
            #pattern: ^/(%multilocales%)(%locdel%)translational-research
            pattern: ^.*/translational-research
            context: scan_auth
            switch_user: true
            custom_authenticators:
                authenticator: custom_guard_authenticator
            form_login:
                login_path: translationalresearch_login
                check_path: translationalresearch_login_check
            logout:
                path:   translationalresearch_logout
                target: translationalresearch_login
                #invalidate_session: false
            lazy: true
            provider: users
            access_denied_url: translationalresearch_access_request_new_plain #/translational-research/access-requests/new/create
            remember_me:
                secret:      "%secret%"
                lifetime: 28800 # 8 hours in seconds
                #path:     /(%multilocales%)(%locdel%)translational-research
                #path:     /translational-research
#                always_remember_me: true

        ldap_dashboard_firewall:
            #pattern: ^/(%multilocales%)(%locdel%)dashboards
            pattern: ^.*/dashboards
            context: scan_auth
            switch_user: true
            custom_authenticators:
                authenticator: custom_guard_authenticator
            form_login:
                login_path: dashboard_login
                check_path: dashboard_login_check
            logout:
                path:   dashboard_logout
                target: dashboard_login
                #invalidate_session: false
            lazy: true
            provider: users
            access_denied_url: dashboard_access_request_new_plain #/dashboards/access-requests/new/create
            remember_me:
                secret:      "%secret%"
                lifetime: 28800 # 8 hours in seconds
                #path:     /(%multilocales%)(%locdel%)dashboards
                #path:     /dashboards

        foscomment_api_firewall:
            #pattern: ^/(%multilocales%)(%locdel%)api
            pattern: ^.*/api
            #logout_on_user_change: true
            context: scan_auth
            provider: users
            lazy: true
            #provider: users
#            remember_me:
#                secret:      "%secret%"
#                lifetime: 604800 # 1 week in seconds
#                path:     /api
#                always_remember_me: true

#        default:
#            anonymous: ~
#            guard:
#                authenticator: custom_guard_authenticator

        ### SAML testing ###
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#        saml:
#            #pattern: ^/saml
#            pattern: ^.*/saml
#            stateless: true
#            custom_authenticator: App\Saml\Security\Authentication\SamlAuthenticator
#        saml_firewall:
#            lazy: true
#            provider: saml_provider

        saml_firewall:
            pattern: ^.*/saml
            context: scan_auth
            lazy: true
            provider: saml_provider
            #custom_authenticator: App\Saml\Security\SamlAuthenticator
            custom_authenticators:
                authenticator: custom_guard_authenticator
            #custom_authenticators:
            #   authenticator: App\Saml\Security\SamlAuthenticator
#            form_login:
#                login_path: employees_login
#                check_path: employees_login_check
            logout:
                path:   logout
                #target: login
#            access_denied_url: employees_access_request_new_plain

        ### EOF SAML testing ###
