<?php

namespace Proxies\__CG__\Oleg\OrderformBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FormVersion extends \Oleg\OrderformBundle\Entity\FormVersion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\FormVersion' . "\0" . 'id', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\FormVersion' . "\0" . 'message', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\FormVersion' . "\0" . 'formId', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\FormVersion' . "\0" . 'formTitle', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\FormVersion' . "\0" . 'formVersion'];
        }

        return ['__isInitialized__', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\FormVersion' . "\0" . 'id', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\FormVersion' . "\0" . 'message', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\FormVersion' . "\0" . 'formId', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\FormVersion' . "\0" . 'formTitle', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\FormVersion' . "\0" . 'formVersion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FormVersion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessage', []);

        return parent::getMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessage($message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessage', [$message]);

        return parent::setMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormId', []);

        return parent::getFormId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormId($formId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormId', [$formId]);

        return parent::setFormId($formId);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormTitle', []);

        return parent::getFormTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormTitle($formTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormTitle', [$formTitle]);

        return parent::setFormTitle($formTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormVersion', []);

        return parent::getFormVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormVersion($formVersion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormVersion', [$formVersion]);

        return parent::setFormVersion($formVersion);
    }

    /**
     * {@inheritDoc}
     */
    public function setFormNode($formNode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormNode', [$formNode]);

        return parent::setFormNode($formNode);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function printShort()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'printShort', []);

        return parent::printShort();
    }

}
