#!/bin/bash

# Source: https://github.com/ZermattChris/Symfony2-SimpleDeployScripts
# Docs: see the accompanying README.md file.

# cd /path/to/simple
# ./deploy1


##### Constants #####

PROJECT_NAME='ScanOrder Symfony2 Project'

# The location of the Symfony2 project you want to Deploy.
PROJECT_LOCAL_PATH=.


##### Functions #####
function prep()
{
    echo "Preparing for Deploy..."

    #for production: git remote update, git pull
    #echo "*** Pull code from git repository ***"
    #git remote update
    #git pull

    echo "*** Update tables in Doctrine DB ***"
    php $PROJECT_LOCAL_PATH/app/console doctrine:schema:update --force

    echo "*** Install assets ***"
    php $PROJECT_LOCAL_PATH/app/console assets:install

    echo "*** Clear cache ***"
    #php $PROJECT_LOCAL_PATH/app/console cache:clear --env=prod --no-debug --no-warmup
    php $PROJECT_LOCAL_PATH/app/console cache:clear --env=prod --no-debug

    echo "*** Dump assets ***"
    php $PROJECT_LOCAL_PATH/app/console assetic:dump --env=prod --no-debug
}


######## Run ########
echo
echo "************* Deploying $PROJECT_NAME *************"
echo

# Prepare for Deploy by clearing the local cache and dumping assetic assets.
prep

echo "Deploy complete."
echo
exit 0