<?php

namespace Oleg\OrderformBundle\Repository;
use Doctrine\ORM\EntityRepository;

//use Oleg\OrderformBundle\Entity\Accession;

/**
 * AccessionRepository
 * This class was generated by the Doctrine ORM.
 * Add your own custom repository methods below.
 */
class AccessionRepository extends EntityRepository {
    
    //this function will create an accession if it doesn't exist or return the existing accession object
    public function processEntity( $accession, $orderinfo ) {

        $entity = $this->findOneBy(array('accession' => $accession->getAccession()));

        $em = $this->_em;

        if( !$entity ) {        
            //create new accession
            //$em->persist($accession);
            return $this->setResult( $accession, $orderinfo );          
        }

        //copy all children to existing entity
//        foreach( $accession->getPart() as $part ) {
//            $entity->addPart( $part );
//        }
//        foreach( $accession->getSlide() as $slide ) {
//            $entity->addSlide( $slide );
//        }

//        $em->persist($entity);
//        return $entity;
        
        return $this->setResult( $entity, $orderinfo );        
    }
    
    public function setResult( $accession, $orderinfo ) {
        
        $em = $this->_em;
        $em->persist($accession); 
        echo "accession=".$accession."<br>";
        
        $parts = $accession->getPart();
        foreach( $parts as $part ) {
            if( !$part->getId() ) {
                $accession->removePart( $part );
                $part = $em->getRepository('OlegOrderformBundle:Part')->processEntity( $part, $accession, $orderinfo );
                $accession->addPart($part);
                $orderinfo->addPart($part);
            } else {
                continue;
            }
        }
                  
        $em->flush($accession);
        
        return $accession;
    }
    
}
?>
