<?php

namespace Oleg\OrderformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRepository extends EntityRepository
{
    
    //this function will create an entity if it doesn't exist or return the existing entity object
    public function processBlock( $block ) {  
        
        $entity = $this->findOneBy( array(
            'name' => $block->getName(),
            'part' => $block->getPart(),
            'accession' => $block->getAccession()
        ));
        
        if (!$entity) {        
            //create new entity           
            $em = $this->_em;
            $em->persist($block);
            $em->flush();
            
            return $block;
        } 
        
        
        return $entity;
    }
    
//    public function getByAccession( $accession_number ) { 
//        
//        $entity = $this->findBy(
//            array('accession' => $accession_number),
//            array('id' => 'ASC')
//        );
//              
//        return $entity;
//    }
    
}
