<?php

namespace Oleg\OrderformBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Oleg\OrderformBundle\Helper\FormHelper;

/**
 * OrderInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderInfoRepository extends EntityRepository
{
    
    //make correct object
    public function processEntity( $entity, $type ) {  
        
        
        $entity->setStatus("active"); 
        $entity->setType($type);  
        
        $helper = new FormHelper();
        
        $slideDelivery = $helper->getSlideDelivery();
        $key = $entity->getSlideDelivery();     
        $entity->setSlideDelivery( $slideDelivery[$key] );
        
        $returnSlide = $helper->getReturnSlide();
        $key = $entity->getReturnSlide();           
        $entity->setReturnSlide( $returnSlide[$key] );
             
        $key = $entity->getPathologyService();   
        if( $key ) {
            $pathologyService = $helper->getPathologyService();
            $entity->setPathologyService( $pathologyService[$key] );
        }
        
        return $entity; 
    }
    
}
