<?php

namespace Oleg\OrderformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SpecimenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecimenRepository extends EntityRepository
{
    
    //Accession number is the key to check uniqueness for single slide order
    public function processEntity( $in_entity, $accessions=null ) {
        
        $em = $this->_em;

        if( $accessions == null ) {
            $em->persist($in_entity);
            return $in_entity;
        }

        $accession_found = null;
        //if at least one accession belongs to a procedure, then use this procedure
        foreach( $accessions as $accession ) {
            //if accession exists then return procedure for this accession; otherwise, create a new
            $accession_found_this = $em->getRepository('OlegOrderformBundle:Accession')->findOneBy( array(
                'accession' => $accession->getAccession()
            ));
            if( $accession_found_this != null && $accession_found_this->getSpecimen() != null ) {
                $accession_found = $accession_found_this;
                break;
            }
        }
        
        if( $accession_found == null || $accession_found->getSpecimen() == null ) {

            $em->persist($in_entity);
            return $in_entity;

        } else {
            $specimen = $accession_found->getSpecimen();

            //copy all children to existing entity
            foreach( $in_entity->getAccession() as $accession ) {
                $specimen->addAccession( $accession );
            }

            $em->persist($specimen);
            return $specimen;
        }
    }
    
}
