<?php

namespace Oleg\OrderformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Oleg\OrderformBundle\Entity\Status;

/**
 * BlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends EntityRepository
{

//  public function setStatus_TODEL( $statusStr ) {
//
//        $em = $this->_em;
//
//        //***********************  USER ACTIONS  ******************************//
//
//        if( $statusStr == "Submit" ) {
//
//            $status = new Status();
//            $status->setName("Submitted");
//            $status->setAction("Submit");
//
//            $status = $em->getRepository('OlegOrderformBundle:Status')->findOneByAction($statusStr);
//
//            $status->setType( $em->getRepository('OlegOrderformBundle:StatusType')->findOneByName('Regular') );
//            $status->setGroup( $em->getRepository('OlegOrderformBundle:StatusGroup')->findOneByName('User') );
//
//            $em->persist($status);
//
//            return $status;
//        }
//
//        if( $statusStr == "On Hold" ) {
//
//            $status = new Status();
//            $status->setName("Not Submitted");
//            $status->setAction("On Hold");
//
//            $status->setType( $em->getRepository('OlegOrderformBundle:StatusType')->findOneByName('Regular') );
//            $status->setGroup( $em->getRepository('OlegOrderformBundle:StatusGroup')->findOneByName('User') );
//
//            $em->persist($status);
//
//            return $status;
//        }
//
//
//        if( $statusStr == "Cancel" ) {
//
//            $status = new Status();
//            $status->setName("Canceled");
//            $status->setAction("Cancel");
//
//            $status->setType( $em->getRepository('OlegOrderformBundle:StatusType')->findOneByName('Regular') );
//            $status->setGroup( $em->getRepository('OlegOrderformBundle:StatusGroup')->findOneByName('User') );
//
//            $em->persist($status);
//
//            return $status;
//        }
//
//
//        if( $statusStr == "Amend" ) {
//
//            $status = new Status();
//            $status->setName("Amended");
//            $status->setAction("Amend");
//
//            $status->setType( $em->getRepository('OlegOrderformBundle:StatusType')->findOneByName('Regular') );
//            $status->setGroup( $em->getRepository('OlegOrderformBundle:StatusGroup')->findOneByName('User') );
//
//            $em->persist($status);
//
//            return $status;
//        }
//
//
//        //***********************  ADMIN ACTIONS  ******************************//
//
//        //Filled
//        if( strpos($statusStr,'Filled') !== false ) {
//
//            $status = new Status();
//            $status->setName($statusStr);
//            $status->setAction($statusStr);
//
//            $status->setType( $em->getRepository('OlegOrderformBundle:StatusType')->findOneByName('Filled') );
//            $status->setGroup( $em->getRepository('OlegOrderformBundle:StatusGroup')->findOneByName('Admin') );
//
//            $em->persist($status);
//
//            return $status;
//        }
//
//        //On Hold
//        if( strpos($statusStr,'On Hold') !== false ) {
//
//            $status = new Status();
//            $status->setName($statusStr);
//            $status->setAction($statusStr);
//
//            $status->setType( $em->getRepository('OlegOrderformBundle:StatusType')->findOneByName('On Hold') );
//            $status->setGroup( $em->getRepository('OlegOrderformBundle:StatusGroup')->findOneByName('Admin') );
//
//            $em->persist($status);
//
//            return $status;
//        }
//
//        return null;
//    }

}