<?php

namespace Oleg\CallLogBundle\Util;

/**
 * Created by PhpStorm.
 * User: ch3
 * Date: 6/10/2016
 * Time: 3:04 PM
 */
class CallLogUtil
{

    protected $em;
    protected $sc;
    protected $container;

    public function __construct( $em, $sc, $container ) {
        $this->em = $em;
        $this->sc = $sc;
        $this->container = $container;
    }


//    public function processMerge( $patientsArr ) {
//
//        foreach( $patientsArr as $patient ) {
//
//
//
//        }
//
//    }


    //auto-generating a unique MRN on Scan Order, but prepend a prefix "MERGE"
    public function autoGenerateMergeMrn( $patient ) {

        $nextKey = $this->em->getRepository('OlegOrderformBundle:Patient')->getNextNonProvided($patient,null,null);

        //convert NOMRNPROVIDED-0000000002 to MERGE-ID-0000000002
        $nextKey = str_replace("NOMRNPROVIDED","",$nextKey);
        $nextKey = "MERGE-ID".$nextKey;
        //echo "nextKey=".$nextKey."<br>";

        return $nextKey;
    }

    public function addGenerateMergeMrnToPatient( $patient, $autoGeneratedMergeMrn, $provider ) {
        $securityUtil = $this->get('order_security_utility');

        //$this->addMrn( new PatientMrn($status,$provider,$sourcesystem) );

        //Source System: Call Log
        $sourcesystem = $securityUtil->getDefaultSourceSystem(); //'scanorder';
        $status = 'valid';
        $newMrn = new PatientMrn($status,$provider,$sourcesystem);

    }


}