<?php

namespace Proxies\__CG__\Oleg\OrderformBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Educational extends \Oleg\OrderformBundle\Entity\Educational implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\Educational' . "\0" . 'id', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\Educational' . "\0" . 'message', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\Educational' . "\0" . 'slides', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\Educational' . "\0" . 'userWrappers', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\Educational' . "\0" . 'courseTitle', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\Educational' . "\0" . 'primaryPrincipal', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\Educational' . "\0" . 'primarySet'];
        }

        return ['__isInitialized__', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\Educational' . "\0" . 'id', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\Educational' . "\0" . 'message', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\Educational' . "\0" . 'slides', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\Educational' . "\0" . 'userWrappers', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\Educational' . "\0" . 'courseTitle', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\Educational' . "\0" . 'primaryPrincipal', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\Educational' . "\0" . 'primarySet'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Educational $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessage($message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessage', [$message]);

        return parent::setMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessage', []);

        return parent::getMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function addSlide(\Oleg\OrderformBundle\Entity\Slide $slide)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSlide', [$slide]);

        return parent::addSlide($slide);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSlide(\Oleg\OrderformBundle\Entity\Slide $slide)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSlide', [$slide]);

        return parent::removeSlide($slide);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlides()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlides', []);

        return parent::getSlides();
    }

    /**
     * {@inheritDoc}
     */
    public function setCourseTitle($courseTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCourseTitle', [$courseTitle]);

        return parent::setCourseTitle($courseTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCourseTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourseTitle', []);

        return parent::getCourseTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserWrappers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserWrappers', []);

        return parent::getUserWrappers();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserWrapper($userWrapper)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserWrapper', [$userWrapper]);

        return parent::addUserWrapper($userWrapper);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserWrapper($userWrappers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserWrapper', [$userWrappers]);

        return parent::removeUserWrapper($userWrappers);
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimarySet($primarySet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimarySet', [$primarySet]);

        return parent::setPrimarySet($primarySet);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimarySet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimarySet', []);

        return parent::getPrimarySet();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimaryPrincipal($primaryPrincipal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimaryPrincipal', [$primaryPrincipal]);

        return parent::setPrimaryPrincipal($primaryPrincipal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimaryPrincipal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimaryPrincipal', []);

        return parent::getPrimaryPrincipal();
    }

    /**
     * {@inheritDoc}
     */
    public function isEmpty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEmpty', []);

        return parent::isEmpty();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
