<?php

namespace Proxies\__CG__\Oleg\OrderformBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CalllogEntryMessage extends \Oleg\OrderformBundle\Entity\CalllogEntryMessage implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'message', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'addPatientToList', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'patientLists', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'entryTags', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'timeSpentMinutes', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'patientLastNameBackup', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'patientFirstNameBackup', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'patientMiddleNameBackup', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'patientDOBBackup', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'patientMRNTypeBackup', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'patientMRNBackup', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'encounterTypeBackup', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'encounterNumberBackup', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'encounterDateBackup', 'id', 'instruction', 'processedDate', 'processedByUser'];
        }

        return ['__isInitialized__', 'message', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'addPatientToList', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'patientLists', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'entryTags', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'timeSpentMinutes', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'patientLastNameBackup', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'patientFirstNameBackup', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'patientMiddleNameBackup', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'patientDOBBackup', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'patientMRNTypeBackup', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'patientMRNBackup', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'encounterTypeBackup', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'encounterNumberBackup', '' . "\0" . 'Oleg\\OrderformBundle\\Entity\\CalllogEntryMessage' . "\0" . 'encounterDateBackup', 'id', 'instruction', 'processedDate', 'processedByUser'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CalllogEntryMessage $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAddPatientToList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddPatientToList', []);

        return parent::getAddPatientToList();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddPatientToList($addPatientToList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddPatientToList', [$addPatientToList]);

        return parent::setAddPatientToList($addPatientToList);
    }

    /**
     * {@inheritDoc}
     */
    public function addPatientList($item)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPatientList', [$item]);

        return parent::addPatientList($item);
    }

    /**
     * {@inheritDoc}
     */
    public function removePatientList($item)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePatientList', [$item]);

        return parent::removePatientList($item);
    }

    /**
     * {@inheritDoc}
     */
    public function getPatientLists()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatientLists', []);

        return parent::getPatientLists();
    }

    /**
     * {@inheritDoc}
     */
    public function addEntryTag($item)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEntryTag', [$item]);

        return parent::addEntryTag($item);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEntryTag($item)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEntryTag', [$item]);

        return parent::removeEntryTag($item);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntryTags()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntryTags', []);

        return parent::getEntryTags();
    }

    /**
     * {@inheritDoc}
     */
    public function getPatientLastNameBackup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatientLastNameBackup', []);

        return parent::getPatientLastNameBackup();
    }

    /**
     * {@inheritDoc}
     */
    public function setPatientLastNameBackup($patientLastNameBackup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatientLastNameBackup', [$patientLastNameBackup]);

        return parent::setPatientLastNameBackup($patientLastNameBackup);
    }

    /**
     * {@inheritDoc}
     */
    public function getPatientFirstNameBackup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatientFirstNameBackup', []);

        return parent::getPatientFirstNameBackup();
    }

    /**
     * {@inheritDoc}
     */
    public function setPatientFirstNameBackup($patientFirstNameBackup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatientFirstNameBackup', [$patientFirstNameBackup]);

        return parent::setPatientFirstNameBackup($patientFirstNameBackup);
    }

    /**
     * {@inheritDoc}
     */
    public function getPatientMiddleNameBackup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatientMiddleNameBackup', []);

        return parent::getPatientMiddleNameBackup();
    }

    /**
     * {@inheritDoc}
     */
    public function setPatientMiddleNameBackup($patientMiddleNameBackup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatientMiddleNameBackup', [$patientMiddleNameBackup]);

        return parent::setPatientMiddleNameBackup($patientMiddleNameBackup);
    }

    /**
     * {@inheritDoc}
     */
    public function getPatientDOBBackup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatientDOBBackup', []);

        return parent::getPatientDOBBackup();
    }

    /**
     * {@inheritDoc}
     */
    public function setPatientDOBBackup($patientDOBBackup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatientDOBBackup', [$patientDOBBackup]);

        return parent::setPatientDOBBackup($patientDOBBackup);
    }

    /**
     * {@inheritDoc}
     */
    public function getPatientMRNTypeBackup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatientMRNTypeBackup', []);

        return parent::getPatientMRNTypeBackup();
    }

    /**
     * {@inheritDoc}
     */
    public function setPatientMRNTypeBackup(\Oleg\OrderformBundle\Entity\MrnType $patientMRNTypeBackup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatientMRNTypeBackup', [$patientMRNTypeBackup]);

        return parent::setPatientMRNTypeBackup($patientMRNTypeBackup);
    }

    /**
     * {@inheritDoc}
     */
    public function getPatientMRNBackup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatientMRNBackup', []);

        return parent::getPatientMRNBackup();
    }

    /**
     * {@inheritDoc}
     */
    public function setPatientMRNBackup($patientMRNBackup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatientMRNBackup', [$patientMRNBackup]);

        return parent::setPatientMRNBackup($patientMRNBackup);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncounterTypeBackup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncounterTypeBackup', []);

        return parent::getEncounterTypeBackup();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncounterTypeBackup(\Oleg\OrderformBundle\Entity\EncounterType $encounterTypeBackup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncounterTypeBackup', [$encounterTypeBackup]);

        return parent::setEncounterTypeBackup($encounterTypeBackup);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncounterNumberBackup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncounterNumberBackup', []);

        return parent::getEncounterNumberBackup();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncounterNumberBackup($encounterNumberBackup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncounterNumberBackup', [$encounterNumberBackup]);

        return parent::setEncounterNumberBackup($encounterNumberBackup);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncounterDateBackup()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncounterDateBackup', []);

        return parent::getEncounterDateBackup();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncounterDateBackup($encounterDateBackup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncounterDateBackup', [$encounterDateBackup]);

        return parent::setEncounterDateBackup($encounterDateBackup);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimeSpentMinutes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimeSpentMinutes', []);

        return parent::getTimeSpentMinutes();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimeSpentMinutes($timeSpentMinutes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimeSpentMinutes', [$timeSpentMinutes]);

        return parent::setTimeSpentMinutes($timeSpentMinutes);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstruction($instruction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstruction', [$instruction]);

        return parent::setInstruction($instruction);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstruction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstruction', []);

        return parent::getInstruction();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessage($message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessage', [$message]);

        return parent::setMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessage', []);

        return parent::getMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setProcessedByUser($processedByUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcessedByUser', [$processedByUser]);

        return parent::setProcessedByUser($processedByUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcessedByUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcessedByUser', []);

        return parent::getProcessedByUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setProcessedDate($processedDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcessedDate', [$processedDate]);

        return parent::setProcessedDate($processedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcessedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcessedDate', []);

        return parent::getProcessedDate();
    }

}
