#Master routes to define prefix and requirements for all routes in one place
#https://stackoverflow.com/questions/11781287/symfony2-route-global-locale-requirements

#Multi tenancy routes
ProjectBaseBundle_localized:
    resource: 'routes-default.yaml'
    schemes:  ['%connection_channel%']
    prefix:   /{_locale}
    #prefix:   /{tenantprefix}
#    prefix:
#        main: '' #default - no prefix
#        c-wcm-pathology: '/c/wcm/pathology'
#        c-lmh-pathology: '/c/lmh/pathology'
    #name_prefix: 'localized_'
    requirements:
        #_locale: en|es|de|fr
        #_locale: '[^.]+'
        _locale: main|c/wcm/pathology|c/lmh/pathology
        #tenantprefix: c/wcm/pathology|c/lmh/pathology

#Locale Switcher: https://symfony.com/blog/new-in-symfony-6-1-locale-switcher
