#Master routes to define prefix and requirements for all routes in one place
#https://stackoverflow.com/questions/11781287/symfony2-route-global-locale-requirements

#framework:
#    default_locale: "main"

#Multi tenancy routes
ProjectBaseBundle_localized:
    resource: 'routes-default.yaml'
    schemes:  ['%connection_channel%']
    prefix:   /{_locale}
    #prefix:
    #    default: '' #default - no prefix
    #    system: 'system'
        #c-lmh-pathology: '/c/lmh/pathology'
    #name_prefix: 'localized_'
    requirements:
        _locale: '%multilocales%'
    defaults:
        _locale: '%defaultlocale%' #'^&'

#Locale Switcher: https://symfony.com/blog/new-in-symfony-6-1-locale-switcher

#set default_locale: "%defaultlocale%" to 'main'
main_multi_home:
    path:      /
    controller: App\SystemBundle\Controller\ExtraController::extra
    schemes:  ['%connection_channel%']

    #defaults:
    #  _locale: '%defaultlocale%'
    #prefix:   /{_locale}
    #requirements:
    #    _locale: main|c/wcm/pathology|c/lmh/pathology

#main_system_home:
#    path:      /system/home
#    controller: App\Routing\Controller\ExtraController::systemHomeAction
#    schemes:  ['%connection_channel%']
#main_system_init:
#    path:      /system/init
#    controller: App\Routing\Controller\ExtraController::systemInitAction
#    schemes:  ['%connection_channel%']
