<?php
/**
 * Copyright (c) 2017 Cornell University
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */


namespace App\FellAppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

#[ORM\Table(name: 'fellapp_siteParameter')]
#[ORM\Entity]
class FellappSiteParameter {

    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    private $id;

    /**
     * Subject of e-mail to the accepted applicant
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private $acceptedEmailSubject;

    /**
     * Subject of e-mail to the accepted applicant
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private $acceptedEmailBody;


    /**
     * Subject of e-mail to the rejected applicant
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private $rejectedEmailSubject;

    /**
     * Subject of e-mail to the rejected applicant
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private $rejectedEmailBody;

    /**
     * Application season start date (MM/DD). default: academicYearStart
     */
    #[ORM\Column(type: 'date', nullable: true)]
    private $fellappAcademicYearStart;

    /**
     * Application season end date (MM/DD). default: academicYearEnd
     */
    #[ORM\Column(type: 'date', nullable: true)]
    private $fellappAcademicYearEnd;
    
    /**
     * the web app url from deployment GAS, send by email in inviteSingleReferenceToSubmitLetter
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private $fellappRecLetterUrl;

    /**
     * Email address for confirmation of application submission
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private $confirmationEmailFellApp;

    /**
     * Link to the Application Page (so the users can click and see how it looks)
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private $applicationPageLinkFellApp;

    /**
     * Rename $p12KeyPathFellApp to $authPathFellApp
     * Full path to the credential authentication JSON file for Google
     * C:\Users\ch3\Documents\MyDocs\WCMC\ORDER\order-lab\orderflex\src\App\FellAppBundle\Util\quickstart-FellowshipAuth.json
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private $authPathFellApp;

    /**
     * Google Drive API URL
     * https://www.googleapis.com/auth/drive https://spreadsheets.google.com/feeds
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private $googleDriveApiUrlFellApp;

    /**
     * $localInstitutionFellApp
     * Local Institution to which every imported application is set: Pathology Fellowship Programs (WCMC)
     */
    #[ORM\ManyToOne(targetEntity: 'App\UserdirectoryBundle\Entity\Institution')]
    private $localInstitutionFellApp;

    /**
     * Modify the filename format generated by the Google recommendation letter upload form to include the “institution name” that is supplied in the URL
     * Institution for which recommendation letters will be downloaded (fellowship identification string).
     * Will be used to filter and only download files that have the matching institution string in the file name.
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private $identificationUploadLetterFellApp;

    /**
     * Recommendation Letter Salt to generate Recommendation Letter Salted Scrypt Hash ID
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private $recLetterSaltFellApp;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private $allowPopulateFellApp;

    /**
     * Automatically send invitation emails to upload recommendation letters
     */
    #[ORM\Column(type: 'boolean', nullable: true)]
    private $sendEmailUploadLetterFellApp;

    #[ORM\Column(type: 'text', nullable: true)]
    private $confirmationSubjectFellApp;

    #[ORM\Column(type: 'text', nullable: true)]
    private $confirmationBodyFellApp;

    /**
     * [ checkbox ] Delete successfully imported applications from Google Drive
     */
    #[ORM\Column(type: 'boolean', nullable: true)]
    private $deleteImportedAplicationsFellApp;

    /**
     * checkbox for "Automatically delete downloaded applications that are older than [X] year(s)
     * (set it at 2) [this is to delete old excel sheets that are downloaded from google drive.
     * Make sure it is functional and Google/Excel sheets containing applications older than
     * the amount of years set by this option is auto-deleted along with the linked downloaded documents.
     */
    #[ORM\Column(type: 'boolean', nullable: true)]
    private $deleteOldAplicationsFellApp;

    /**
     * Used in checkbox for "Automatically delete downloaded applications that are older than [X] year(s)
     */
    #[ORM\Column(type: 'integer', nullable: true)]
    private $yearsOldAplicationsFellApp;

    /**
     * Path to spreadsheets: i.e. Spreadsheets
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private $spreadsheetsPathFellApp;

    /**
     * Path to upload applicants documents: i.e. FellowshipApplicantUploads
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private $applicantsUploadPathFellApp;


    /**
     * Path to upload applicants documents used in ReportGenerator: i.e. Reports
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private $reportsUploadPathFellApp;

    // Enable access to the fellowship application form page on this site via /fellowship-applications/apply and enable recommendation letter upload via /fellowship-applications/submit-recommendation
    //Enable access to the fellowship application form page on this site
    #[ORM\Column(type: 'boolean', nullable: true)]
    private $enablePublicFellApp;

    
    public function __construct() {
        $this->setAllowPopulateFellApp(false);
        $this->setSendEmailUploadLetterFellApp(false);
        $this->setDeleteImportedAplicationsFellApp(false);
        $this->setDeleteOldAplicationsFellApp(false);
        $this->setEnablePublicFellApp(false);
    }



    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getAcceptedEmailSubject()
    {
        return $this->acceptedEmailSubject;
    }

    /**
     * @param mixed $acceptedEmailSubject
     */
    public function setAcceptedEmailSubject($acceptedEmailSubject)
    {
        $this->acceptedEmailSubject = $acceptedEmailSubject;
    }

    /**
     * @return mixed
     */
    public function getAcceptedEmailBody()
    {
        return $this->acceptedEmailBody;
    }

    /**
     * @param mixed $acceptedEmailBody
     */
    public function setAcceptedEmailBody($acceptedEmailBody)
    {
        $this->acceptedEmailBody = $acceptedEmailBody;
    }

    /**
     * @return mixed
     */
    public function getRejectedEmailSubject()
    {
        return $this->rejectedEmailSubject;
    }

    /**
     * @param mixed $rejectedEmailSubject
     */
    public function setRejectedEmailSubject($rejectedEmailSubject)
    {
        $this->rejectedEmailSubject = $rejectedEmailSubject;
    }

    /**
     * @return mixed
     */
    public function getRejectedEmailBody()
    {
        return $this->rejectedEmailBody;
    }

    /**
     * @param mixed $rejectedEmailBody
     */
    public function setRejectedEmailBody($rejectedEmailBody)
    {
        $this->rejectedEmailBody = $rejectedEmailBody;
    }

    /**
     * @return mixed
     */
    public function getFellappAcademicYearStart()
    {
        return $this->fellappAcademicYearStart;
    }

    /**
     * @param mixed $fellappAcademicYearStart
     */
    public function setFellappAcademicYearStart($fellappAcademicYearStart)
    {
        $this->fellappAcademicYearStart = $fellappAcademicYearStart;
    }

    /**
     * @return mixed
     */
    public function getFellappAcademicYearEnd()
    {
        return $this->fellappAcademicYearEnd;
    }

    /**
     * @param mixed $fellappAcademicYearEnd
     */
    public function setFellappAcademicYearEnd($fellappAcademicYearEnd)
    {
        $this->fellappAcademicYearEnd = $fellappAcademicYearEnd;
    }

    /**
     * @return mixed
     */
    public function getFellappRecLetterUrl()
    {
        return $this->fellappRecLetterUrl;
    }

    /**
     * @param mixed $fellappRecLetterUrl
     */
    public function setFellappRecLetterUrl($fellappRecLetterUrl)
    {
        $this->fellappRecLetterUrl = $fellappRecLetterUrl;
    }

    /**
     * @return mixed
     */
    public function getConfirmationEmailFellApp()
    {
        return $this->confirmationEmailFellApp;
    }

    /**
     * @param mixed $confirmationEmailFellApp
     */
    public function setConfirmationEmailFellApp($confirmationEmailFellApp)
    {
        $this->confirmationEmailFellApp = $confirmationEmailFellApp;
    }

    /**
     * @return mixed
     */
    public function getApplicationPageLinkFellApp()
    {
        return $this->applicationPageLinkFellApp;
    }

    /**
     * @param mixed $applicationPageLinkFellApp
     */
    public function setApplicationPageLinkFellApp($applicationPageLinkFellApp)
    {
        $this->applicationPageLinkFellApp = $applicationPageLinkFellApp;
    }

    /**
     * @return mixed
     */
    public function getAuthPathFellApp()
    {
        return $this->authPathFellApp;
    }

    /**
     * @param mixed $authPathFellApp
     */
    public function setAuthPathFellApp($authPathFellApp)
    {
        $this->authPathFellApp = $authPathFellApp;
    }

    /**
     * @return mixed
     */
    public function getGoogleDriveApiUrlFellApp()
    {
        return $this->googleDriveApiUrlFellApp;
    }

    /**
     * @param mixed $googleDriveApiUrlFellApp
     */
    public function setGoogleDriveApiUrlFellApp($googleDriveApiUrlFellApp)
    {
        $this->googleDriveApiUrlFellApp = $googleDriveApiUrlFellApp;
    }

    /**
     * @return mixed
     */
    public function getLocalInstitutionFellApp()
    {
        return $this->localInstitutionFellApp;
    }

    /**
     * @param mixed $localInstitutionFellApp
     */
    public function setLocalInstitutionFellApp($localInstitutionFellApp)
    {
        $this->localInstitutionFellApp = $localInstitutionFellApp;
    }

    /**
     * @return mixed
     */
    public function getIdentificationUploadLetterFellApp()
    {
        return $this->identificationUploadLetterFellApp;
    }

    /**
     * @param mixed $identificationUploadLetterFellApp
     */
    public function setIdentificationUploadLetterFellApp($identificationUploadLetterFellApp)
    {
        $this->identificationUploadLetterFellApp = $identificationUploadLetterFellApp;
    }

    /**
     * @return mixed
     */
    public function getRecLetterSaltFellApp()
    {
        return $this->recLetterSaltFellApp;
    }

    /**
     * @param mixed $recLetterSaltFellApp
     */
    public function setRecLetterSaltFellApp($recLetterSaltFellApp)
    {
        $this->recLetterSaltFellApp = $recLetterSaltFellApp;
    }

    /**
     * @return mixed
     */
    public function getAllowPopulateFellApp()
    {
        return $this->allowPopulateFellApp;
    }

    /**
     * @param mixed $allowPopulateFellApp
     */
    public function setAllowPopulateFellApp($allowPopulateFellApp)
    {
        $this->allowPopulateFellApp = $allowPopulateFellApp;
    }

    /**
     * @return mixed
     */
    public function getSendEmailUploadLetterFellApp()
    {
        return $this->sendEmailUploadLetterFellApp;
    }

    /**
     * @param mixed $sendEmailUploadLetterFellApp
     */
    public function setSendEmailUploadLetterFellApp($sendEmailUploadLetterFellApp)
    {
        $this->sendEmailUploadLetterFellApp = $sendEmailUploadLetterFellApp;
    }

    /**
     * @return mixed
     */
    public function getConfirmationSubjectFellApp()
    {
        return $this->confirmationSubjectFellApp;
    }

    /**
     * @param mixed $confirmationSubjectFellApp
     */
    public function setConfirmationSubjectFellApp($confirmationSubjectFellApp)
    {
        $this->confirmationSubjectFellApp = $confirmationSubjectFellApp;
    }

    /**
     * @return mixed
     */
    public function getConfirmationBodyFellApp()
    {
        return $this->confirmationBodyFellApp;
    }

    /**
     * @param mixed $confirmationBodyFellApp
     */
    public function setConfirmationBodyFellApp($confirmationBodyFellApp)
    {
        $this->confirmationBodyFellApp = $confirmationBodyFellApp;
    }

    /**
     * @return mixed
     */
    public function getDeleteImportedAplicationsFellApp()
    {
        return $this->deleteImportedAplicationsFellApp;
    }

    /**
     * @param mixed $deleteImportedAplicationsFellApp
     */
    public function setDeleteImportedAplicationsFellApp($deleteImportedAplicationsFellApp)
    {
        $this->deleteImportedAplicationsFellApp = $deleteImportedAplicationsFellApp;
    }

    /**
     * @return mixed
     */
    public function getDeleteOldAplicationsFellApp()
    {
        return $this->deleteOldAplicationsFellApp;
    }

    /**
     * @param mixed $deleteOldAplicationsFellApp
     */
    public function setDeleteOldAplicationsFellApp($deleteOldAplicationsFellApp)
    {
        $this->deleteOldAplicationsFellApp = $deleteOldAplicationsFellApp;
    }

    /**
     * @return mixed
     */
    public function getYearsOldAplicationsFellApp()
    {
        return $this->yearsOldAplicationsFellApp;
    }

    /**
     * @param mixed $yearsOldAplicationsFellApp
     */
    public function setYearsOldAplicationsFellApp($yearsOldAplicationsFellApp)
    {
        $this->yearsOldAplicationsFellApp = $yearsOldAplicationsFellApp;
    }

    /**
     * @return mixed
     */
    public function getSpreadsheetsPathFellApp()
    {
        return $this->spreadsheetsPathFellApp;
    }

    /**
     * @param mixed $spreadsheetsPathFellApp
     */
    public function setSpreadsheetsPathFellApp($spreadsheetsPathFellApp)
    {
        $this->spreadsheetsPathFellApp = $spreadsheetsPathFellApp;
    }

    /**
     * @return mixed
     */
    public function getApplicantsUploadPathFellApp()
    {
        return $this->applicantsUploadPathFellApp;
    }

    /**
     * @param mixed $applicantsUploadPathFellApp
     */
    public function setApplicantsUploadPathFellApp($applicantsUploadPathFellApp)
    {
        $this->applicantsUploadPathFellApp = $applicantsUploadPathFellApp;
    }

    /**
     * @return mixed
     */
    public function getReportsUploadPathFellApp()
    {
        return $this->reportsUploadPathFellApp;
    }

    /**
     * @param mixed $reportsUploadPathFellApp
     */
    public function setReportsUploadPathFellApp($reportsUploadPathFellApp)
    {
        $this->reportsUploadPathFellApp = $reportsUploadPathFellApp;
    }

    /**
     * @return mixed
     */
    public function getEnablePublicFellApp()
    {
        return $this->enablePublicFellApp;
    }

    /**
     * @param mixed $enablePublicFellApp
     */
    public function setEnablePublicFellApp($enablePublicFellApp)
    {
        $this->enablePublicFellApp = $enablePublicFellApp;
    }







}

