<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20191126170346 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE transres_adminreview_comment DROP FOREIGN KEY FK_F8416A6EF8697D13');
        $this->addSql('ALTER TABLE transres_committeereview_comment DROP FOREIGN KEY FK_2F1B16BBF8697D13');
        $this->addSql('ALTER TABLE transres_finalreview_comment DROP FOREIGN KEY FK_C9DB5B94F8697D13');
        $this->addSql('ALTER TABLE transres_irbreview_comment DROP FOREIGN KEY FK_C938B9BBF8697D13');
        $this->addSql('ALTER TABLE scan_accountrequest_institution DROP FOREIGN KEY FK_64BCA581427EB8A5');
        $this->addSql('ALTER TABLE scan_encounterStatus DROP FOREIGN KEY FK_C7097D4A108B7592');
        $this->addSql('ALTER TABLE scan_accountrequest DROP FOREIGN KEY FK_F67E4A451466E16');
        $this->addSql('ALTER TABLE scan_systemAccountRequestType DROP FOREIGN KEY FK_DC93409C108B7592');
        $this->addSql('ALTER TABLE user_custom10List DROP FOREIGN KEY FK_D3822DE0108B7592');
        $this->addSql('ALTER TABLE user_custom1List DROP FOREIGN KEY FK_6A959F62108B7592');
        $this->addSql('ALTER TABLE user_custom2List DROP FOREIGN KEY FK_2D35E5B2108B7592');
        $this->addSql('ALTER TABLE user_custom3List DROP FOREIGN KEY FK_1055CC02108B7592');
        $this->addSql('ALTER TABLE user_custom4List DROP FOREIGN KEY FK_A2751012108B7592');
        $this->addSql('ALTER TABLE user_custom5List DROP FOREIGN KEY FK_9F1539A2108B7592');
        $this->addSql('ALTER TABLE user_custom6List DROP FOREIGN KEY FK_D8B54372108B7592');
        $this->addSql('ALTER TABLE user_custom7List DROP FOREIGN KEY FK_E5D56AC2108B7592');
        $this->addSql('ALTER TABLE user_custom8List DROP FOREIGN KEY FK_6785FD13108B7592');
        $this->addSql('ALTER TABLE user_custom9List DROP FOREIGN KEY FK_5AE5D4A3108B7592');
        $this->addSql('ALTER TABLE user_daysList DROP FOREIGN KEY FK_AB2E9C55108B7592');
        $this->addSql('DROP TABLE FosComment');
        $this->addSql('DROP TABLE calllog_message_document');
        $this->addSql('DROP TABLE scan_accountrequest');
        $this->addSql('DROP TABLE scan_accountrequest_institution');
        $this->addSql('DROP TABLE scan_encounterStatus');
        $this->addSql('DROP TABLE scan_systemAccountRequestType');
        $this->addSql('DROP TABLE transres_adminreview_comment');
        $this->addSql('DROP TABLE transres_committeereview_comment');
        $this->addSql('DROP TABLE transres_finalreview_comment');
        $this->addSql('DROP TABLE transres_invoiceAddItem');
        $this->addSql('DROP TABLE transres_irbreview_comment');
        $this->addSql('DROP TABLE user_custom10List');
        $this->addSql('DROP TABLE user_custom1List');
        $this->addSql('DROP TABLE user_custom2List');
        $this->addSql('DROP TABLE user_custom3List');
        $this->addSql('DROP TABLE user_custom4List');
        $this->addSql('DROP TABLE user_custom5List');
        $this->addSql('DROP TABLE user_custom6List');
        $this->addSql('DROP TABLE user_custom7List');
        $this->addSql('DROP TABLE user_custom8List');
        $this->addSql('DROP TABLE user_custom9List');
        $this->addSql('DROP TABLE user_daysList');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE FosComment (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE calllog_message_document (message_id INT NOT NULL, document_id INT NOT NULL, UNIQUE INDEX UNIQ_2F3D3005C33F7837 (document_id), INDEX IDX_2F3D3005537A1329 (message_id), PRIMARY KEY(message_id, document_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE scan_accountrequest (id INT AUTO_INCREMENT NOT NULL, institution_id INT DEFAULT NULL, cwid VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, username VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, hascwid VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, firstName VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, email VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, phone VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, job VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, request LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, similaruser LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, primaryService VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, status VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, creationdate DATETIME DEFAULT NULL, actiondate DATETIME DEFAULT NULL, referencename VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, referenceemail VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, referencephone VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, systemAccountRequest_id INT DEFAULT NULL, INDEX IDX_F67E4A410405986 (institution_id), INDEX IDX_F67E4A451466E16 (systemAccountRequest_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE scan_accountrequest_institution (request_id INT NOT NULL, institution_id INT NOT NULL, INDEX IDX_64BCA581427EB8A5 (request_id), INDEX IDX_64BCA58110405986 (institution_id), PRIMARY KEY(request_id, institution_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE scan_encounterStatus (id INT AUTO_INCREMENT NOT NULL, original_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, updatedby_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, abbreviation VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shortname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, createdate DATETIME DEFAULT NULL, updatedon DATETIME DEFAULT NULL, orderinlist INT NOT NULL, updateAuthorRoles LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:array)\', fulltitle VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, linkToListId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityNamespace VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityName VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, objectType_id INT DEFAULT NULL, INDEX IDX_C7097D4A108B7592 (original_id), INDEX IDX_C7097D4A61220EA6 (creator_id), INDEX IDX_C7097D4AA43E35E8 (updatedby_id), INDEX IDX_C7097D4ABD42F28C (objectType_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE scan_systemAccountRequestType (id INT AUTO_INCREMENT NOT NULL, original_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, updatedby_id INT DEFAULT NULL, entityNamespace VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, abbreviation VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shortname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, createdate DATETIME DEFAULT NULL, updatedon DATETIME DEFAULT NULL, orderinlist INT NOT NULL, updateAuthorRoles LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:array)\', fulltitle VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, linkToListId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, objectType_id INT DEFAULT NULL, entityName VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, version INT DEFAULT NULL, INDEX IDX_DC93409C108B7592 (original_id), INDEX IDX_DC93409C61220EA6 (creator_id), INDEX IDX_DC93409CA43E35E8 (updatedby_id), INDEX IDX_DC93409CBD42F28C (objectType_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transres_adminreview_comment (review_id INT NOT NULL, comment_id INT NOT NULL, INDEX IDX_F8416A6E3E2E969B (review_id), INDEX IDX_F8416A6EF8697D13 (comment_id), PRIMARY KEY(review_id, comment_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transres_committeereview_comment (review_id INT NOT NULL, comment_id INT NOT NULL, INDEX IDX_2F1B16BB3E2E969B (review_id), INDEX IDX_2F1B16BBF8697D13 (comment_id), PRIMARY KEY(review_id, comment_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transres_finalreview_comment (review_id INT NOT NULL, comment_id INT NOT NULL, INDEX IDX_C9DB5B943E2E969B (review_id), INDEX IDX_C9DB5B94F8697D13 (comment_id), PRIMARY KEY(review_id, comment_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transres_invoiceAddItem (id INT AUTO_INCREMENT NOT NULL, invoice_id INT DEFAULT NULL, submitter_id INT DEFAULT NULL, createDate DATETIME DEFAULT NULL, updateDate DATETIME DEFAULT NULL, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, fee VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, updateUser INT DEFAULT NULL, INDEX IDX_4A1C5CF0919E5513 (submitter_id), INDEX IDX_4A1C5CF0B7AD1DEE (updateUser), INDEX IDX_4A1C5CF02989F1FD (invoice_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transres_irbreview_comment (review_id INT NOT NULL, comment_id INT NOT NULL, INDEX IDX_C938B9BB3E2E969B (review_id), INDEX IDX_C938B9BBF8697D13 (comment_id), PRIMARY KEY(review_id, comment_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_custom10List (id INT AUTO_INCREMENT NOT NULL, original_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, updatedby_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, abbreviation VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shortname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, createdate DATETIME DEFAULT NULL, updatedon DATETIME DEFAULT NULL, orderinlist INT NOT NULL, updateAuthorRoles LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:array)\', fulltitle VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, linkToListId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityNamespace VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityName VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, version INT DEFAULT NULL, objectType_id INT DEFAULT NULL, INDEX IDX_D3822DE0108B7592 (original_id), INDEX IDX_D3822DE061220EA6 (creator_id), INDEX IDX_D3822DE0A43E35E8 (updatedby_id), INDEX IDX_D3822DE0BD42F28C (objectType_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_custom1List (id INT AUTO_INCREMENT NOT NULL, original_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, updatedby_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, abbreviation VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shortname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, createdate DATETIME DEFAULT NULL, updatedon DATETIME DEFAULT NULL, orderinlist INT NOT NULL, updateAuthorRoles LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:array)\', fulltitle VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, linkToListId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityNamespace VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityName VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, version INT DEFAULT NULL, objectType_id INT DEFAULT NULL, INDEX IDX_6A959F62108B7592 (original_id), INDEX IDX_6A959F6261220EA6 (creator_id), INDEX IDX_6A959F62A43E35E8 (updatedby_id), INDEX IDX_6A959F62BD42F28C (objectType_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_custom2List (id INT AUTO_INCREMENT NOT NULL, original_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, updatedby_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, abbreviation VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shortname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, createdate DATETIME DEFAULT NULL, updatedon DATETIME DEFAULT NULL, orderinlist INT NOT NULL, updateAuthorRoles LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:array)\', fulltitle VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, linkToListId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityNamespace VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityName VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, version INT DEFAULT NULL, objectType_id INT DEFAULT NULL, INDEX IDX_2D35E5B2108B7592 (original_id), INDEX IDX_2D35E5B261220EA6 (creator_id), INDEX IDX_2D35E5B2A43E35E8 (updatedby_id), INDEX IDX_2D35E5B2BD42F28C (objectType_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_custom3List (id INT AUTO_INCREMENT NOT NULL, original_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, updatedby_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, abbreviation VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shortname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, createdate DATETIME DEFAULT NULL, updatedon DATETIME DEFAULT NULL, orderinlist INT NOT NULL, updateAuthorRoles LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:array)\', fulltitle VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, linkToListId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityNamespace VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityName VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, version INT DEFAULT NULL, objectType_id INT DEFAULT NULL, INDEX IDX_1055CC02108B7592 (original_id), INDEX IDX_1055CC0261220EA6 (creator_id), INDEX IDX_1055CC02A43E35E8 (updatedby_id), INDEX IDX_1055CC02BD42F28C (objectType_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_custom4List (id INT AUTO_INCREMENT NOT NULL, original_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, updatedby_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, abbreviation VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shortname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, createdate DATETIME DEFAULT NULL, updatedon DATETIME DEFAULT NULL, orderinlist INT NOT NULL, updateAuthorRoles LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:array)\', fulltitle VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, linkToListId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityNamespace VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityName VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, version INT DEFAULT NULL, objectType_id INT DEFAULT NULL, INDEX IDX_A2751012108B7592 (original_id), INDEX IDX_A275101261220EA6 (creator_id), INDEX IDX_A2751012A43E35E8 (updatedby_id), INDEX IDX_A2751012BD42F28C (objectType_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_custom5List (id INT AUTO_INCREMENT NOT NULL, original_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, updatedby_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, abbreviation VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shortname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, createdate DATETIME DEFAULT NULL, updatedon DATETIME DEFAULT NULL, orderinlist INT NOT NULL, updateAuthorRoles LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:array)\', fulltitle VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, linkToListId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityNamespace VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityName VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, version INT DEFAULT NULL, objectType_id INT DEFAULT NULL, INDEX IDX_9F1539A2108B7592 (original_id), INDEX IDX_9F1539A261220EA6 (creator_id), INDEX IDX_9F1539A2A43E35E8 (updatedby_id), INDEX IDX_9F1539A2BD42F28C (objectType_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_custom6List (id INT AUTO_INCREMENT NOT NULL, original_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, updatedby_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, abbreviation VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shortname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, createdate DATETIME DEFAULT NULL, updatedon DATETIME DEFAULT NULL, orderinlist INT NOT NULL, updateAuthorRoles LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:array)\', fulltitle VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, linkToListId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityNamespace VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityName VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, version INT DEFAULT NULL, objectType_id INT DEFAULT NULL, INDEX IDX_D8B54372108B7592 (original_id), INDEX IDX_D8B5437261220EA6 (creator_id), INDEX IDX_D8B54372A43E35E8 (updatedby_id), INDEX IDX_D8B54372BD42F28C (objectType_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_custom7List (id INT AUTO_INCREMENT NOT NULL, original_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, updatedby_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, abbreviation VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shortname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, createdate DATETIME DEFAULT NULL, updatedon DATETIME DEFAULT NULL, orderinlist INT NOT NULL, updateAuthorRoles LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:array)\', fulltitle VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, linkToListId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityNamespace VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityName VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, version INT DEFAULT NULL, objectType_id INT DEFAULT NULL, INDEX IDX_E5D56AC2108B7592 (original_id), INDEX IDX_E5D56AC261220EA6 (creator_id), INDEX IDX_E5D56AC2A43E35E8 (updatedby_id), INDEX IDX_E5D56AC2BD42F28C (objectType_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_custom8List (id INT AUTO_INCREMENT NOT NULL, original_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, updatedby_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, abbreviation VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shortname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, createdate DATETIME DEFAULT NULL, updatedon DATETIME DEFAULT NULL, orderinlist INT NOT NULL, updateAuthorRoles LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:array)\', fulltitle VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, linkToListId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityNamespace VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityName VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, version INT DEFAULT NULL, objectType_id INT DEFAULT NULL, INDEX IDX_6785FD13108B7592 (original_id), INDEX IDX_6785FD1361220EA6 (creator_id), INDEX IDX_6785FD13A43E35E8 (updatedby_id), INDEX IDX_6785FD13BD42F28C (objectType_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_custom9List (id INT AUTO_INCREMENT NOT NULL, original_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, updatedby_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, abbreviation VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shortname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, createdate DATETIME DEFAULT NULL, updatedon DATETIME DEFAULT NULL, orderinlist INT NOT NULL, updateAuthorRoles LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:array)\', fulltitle VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, linkToListId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityNamespace VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityName VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, version INT DEFAULT NULL, objectType_id INT DEFAULT NULL, INDEX IDX_5AE5D4A3108B7592 (original_id), INDEX IDX_5AE5D4A361220EA6 (creator_id), INDEX IDX_5AE5D4A3A43E35E8 (updatedby_id), INDEX IDX_5AE5D4A3BD42F28C (objectType_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_daysList (id INT AUTO_INCREMENT NOT NULL, original_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, updatedby_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, abbreviation VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shortname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, createdate DATETIME DEFAULT NULL, updatedon DATETIME DEFAULT NULL, orderinlist INT NOT NULL, updateAuthorRoles LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:array)\', fulltitle VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, linkToListId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityId VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityNamespace VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, entityName VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, objectType_id INT DEFAULT NULL, INDEX IDX_AB2E9C55108B7592 (original_id), INDEX IDX_AB2E9C5561220EA6 (creator_id), INDEX IDX_AB2E9C55A43E35E8 (updatedby_id), INDEX IDX_AB2E9C55BD42F28C (objectType_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE calllog_message_document ADD CONSTRAINT FK_2F3D3005537A1329 FOREIGN KEY (message_id) REFERENCES scan_calllogEntryMessage (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE calllog_message_document ADD CONSTRAINT FK_2F3D3005C33F7837 FOREIGN KEY (document_id) REFERENCES user_document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE scan_accountrequest ADD CONSTRAINT FK_F67E4A410405986 FOREIGN KEY (institution_id) REFERENCES user_institution (id)');
        $this->addSql('ALTER TABLE scan_accountrequest ADD CONSTRAINT FK_F67E4A451466E16 FOREIGN KEY (systemAccountRequest_id) REFERENCES scan_systemAccountRequestType (id)');
        $this->addSql('ALTER TABLE scan_accountrequest_institution ADD CONSTRAINT FK_64BCA58110405986 FOREIGN KEY (institution_id) REFERENCES user_institution (id)');
        $this->addSql('ALTER TABLE scan_accountrequest_institution ADD CONSTRAINT FK_64BCA581427EB8A5 FOREIGN KEY (request_id) REFERENCES scan_accountrequest (id)');
        $this->addSql('ALTER TABLE scan_encounterStatus ADD CONSTRAINT FK_C7097D4A108B7592 FOREIGN KEY (original_id) REFERENCES scan_encounterStatus (id)');
        $this->addSql('ALTER TABLE scan_encounterStatus ADD CONSTRAINT FK_C7097D4A61220EA6 FOREIGN KEY (creator_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE scan_encounterStatus ADD CONSTRAINT FK_C7097D4AA43E35E8 FOREIGN KEY (updatedby_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE scan_encounterStatus ADD CONSTRAINT FK_C7097D4ABD42F28C FOREIGN KEY (objectType_id) REFERENCES user_objectTypeList (id)');
        $this->addSql('ALTER TABLE scan_systemAccountRequestType ADD CONSTRAINT FK_DC93409C108B7592 FOREIGN KEY (original_id) REFERENCES scan_systemAccountRequestType (id)');
        $this->addSql('ALTER TABLE scan_systemAccountRequestType ADD CONSTRAINT FK_DC93409C61220EA6 FOREIGN KEY (creator_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE scan_systemAccountRequestType ADD CONSTRAINT FK_DC93409CA43E35E8 FOREIGN KEY (updatedby_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE scan_systemAccountRequestType ADD CONSTRAINT FK_DC93409CBD42F28C FOREIGN KEY (objectType_id) REFERENCES user_objectTypeList (id)');
        $this->addSql('ALTER TABLE transres_adminreview_comment ADD CONSTRAINT FK_F8416A6E3E2E969B FOREIGN KEY (review_id) REFERENCES transres_adminReview (id)');
        $this->addSql('ALTER TABLE transres_adminreview_comment ADD CONSTRAINT FK_F8416A6EF8697D13 FOREIGN KEY (comment_id) REFERENCES FosComment (id)');
        $this->addSql('ALTER TABLE transres_committeereview_comment ADD CONSTRAINT FK_2F1B16BB3E2E969B FOREIGN KEY (review_id) REFERENCES transres_committeeReview (id)');
        $this->addSql('ALTER TABLE transres_committeereview_comment ADD CONSTRAINT FK_2F1B16BBF8697D13 FOREIGN KEY (comment_id) REFERENCES FosComment (id)');
        $this->addSql('ALTER TABLE transres_finalreview_comment ADD CONSTRAINT FK_C9DB5B943E2E969B FOREIGN KEY (review_id) REFERENCES transres_finalReview (id)');
        $this->addSql('ALTER TABLE transres_finalreview_comment ADD CONSTRAINT FK_C9DB5B94F8697D13 FOREIGN KEY (comment_id) REFERENCES FosComment (id)');
        $this->addSql('ALTER TABLE transres_invoiceAddItem ADD CONSTRAINT FK_4A1C5CF02989F1FD FOREIGN KEY (invoice_id) REFERENCES transres_invoice (id)');
        $this->addSql('ALTER TABLE transres_invoiceAddItem ADD CONSTRAINT FK_4A1C5CF0919E5513 FOREIGN KEY (submitter_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE transres_invoiceAddItem ADD CONSTRAINT FK_4A1C5CF0B7AD1DEE FOREIGN KEY (updateUser) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE transres_irbreview_comment ADD CONSTRAINT FK_C938B9BB3E2E969B FOREIGN KEY (review_id) REFERENCES transres_irbReview (id)');
        $this->addSql('ALTER TABLE transres_irbreview_comment ADD CONSTRAINT FK_C938B9BBF8697D13 FOREIGN KEY (comment_id) REFERENCES FosComment (id)');
        $this->addSql('ALTER TABLE user_custom10List ADD CONSTRAINT FK_D3822DE0108B7592 FOREIGN KEY (original_id) REFERENCES user_custom10List (id)');
        $this->addSql('ALTER TABLE user_custom10List ADD CONSTRAINT FK_D3822DE061220EA6 FOREIGN KEY (creator_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom10List ADD CONSTRAINT FK_D3822DE0A43E35E8 FOREIGN KEY (updatedby_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom10List ADD CONSTRAINT FK_D3822DE0BD42F28C FOREIGN KEY (objectType_id) REFERENCES user_objectTypeList (id)');
        $this->addSql('ALTER TABLE user_custom1List ADD CONSTRAINT FK_6A959F62108B7592 FOREIGN KEY (original_id) REFERENCES user_custom1List (id)');
        $this->addSql('ALTER TABLE user_custom1List ADD CONSTRAINT FK_6A959F6261220EA6 FOREIGN KEY (creator_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom1List ADD CONSTRAINT FK_6A959F62A43E35E8 FOREIGN KEY (updatedby_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom1List ADD CONSTRAINT FK_6A959F62BD42F28C FOREIGN KEY (objectType_id) REFERENCES user_objectTypeList (id)');
        $this->addSql('ALTER TABLE user_custom2List ADD CONSTRAINT FK_2D35E5B2108B7592 FOREIGN KEY (original_id) REFERENCES user_custom2List (id)');
        $this->addSql('ALTER TABLE user_custom2List ADD CONSTRAINT FK_2D35E5B261220EA6 FOREIGN KEY (creator_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom2List ADD CONSTRAINT FK_2D35E5B2A43E35E8 FOREIGN KEY (updatedby_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom2List ADD CONSTRAINT FK_2D35E5B2BD42F28C FOREIGN KEY (objectType_id) REFERENCES user_objectTypeList (id)');
        $this->addSql('ALTER TABLE user_custom3List ADD CONSTRAINT FK_1055CC02108B7592 FOREIGN KEY (original_id) REFERENCES user_custom3List (id)');
        $this->addSql('ALTER TABLE user_custom3List ADD CONSTRAINT FK_1055CC0261220EA6 FOREIGN KEY (creator_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom3List ADD CONSTRAINT FK_1055CC02A43E35E8 FOREIGN KEY (updatedby_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom3List ADD CONSTRAINT FK_1055CC02BD42F28C FOREIGN KEY (objectType_id) REFERENCES user_objectTypeList (id)');
        $this->addSql('ALTER TABLE user_custom4List ADD CONSTRAINT FK_A2751012108B7592 FOREIGN KEY (original_id) REFERENCES user_custom4List (id)');
        $this->addSql('ALTER TABLE user_custom4List ADD CONSTRAINT FK_A275101261220EA6 FOREIGN KEY (creator_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom4List ADD CONSTRAINT FK_A2751012A43E35E8 FOREIGN KEY (updatedby_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom4List ADD CONSTRAINT FK_A2751012BD42F28C FOREIGN KEY (objectType_id) REFERENCES user_objectTypeList (id)');
        $this->addSql('ALTER TABLE user_custom5List ADD CONSTRAINT FK_9F1539A2108B7592 FOREIGN KEY (original_id) REFERENCES user_custom5List (id)');
        $this->addSql('ALTER TABLE user_custom5List ADD CONSTRAINT FK_9F1539A261220EA6 FOREIGN KEY (creator_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom5List ADD CONSTRAINT FK_9F1539A2A43E35E8 FOREIGN KEY (updatedby_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom5List ADD CONSTRAINT FK_9F1539A2BD42F28C FOREIGN KEY (objectType_id) REFERENCES user_objectTypeList (id)');
        $this->addSql('ALTER TABLE user_custom6List ADD CONSTRAINT FK_D8B54372108B7592 FOREIGN KEY (original_id) REFERENCES user_custom6List (id)');
        $this->addSql('ALTER TABLE user_custom6List ADD CONSTRAINT FK_D8B5437261220EA6 FOREIGN KEY (creator_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom6List ADD CONSTRAINT FK_D8B54372A43E35E8 FOREIGN KEY (updatedby_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom6List ADD CONSTRAINT FK_D8B54372BD42F28C FOREIGN KEY (objectType_id) REFERENCES user_objectTypeList (id)');
        $this->addSql('ALTER TABLE user_custom7List ADD CONSTRAINT FK_E5D56AC2108B7592 FOREIGN KEY (original_id) REFERENCES user_custom7List (id)');
        $this->addSql('ALTER TABLE user_custom7List ADD CONSTRAINT FK_E5D56AC261220EA6 FOREIGN KEY (creator_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom7List ADD CONSTRAINT FK_E5D56AC2A43E35E8 FOREIGN KEY (updatedby_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom7List ADD CONSTRAINT FK_E5D56AC2BD42F28C FOREIGN KEY (objectType_id) REFERENCES user_objectTypeList (id)');
        $this->addSql('ALTER TABLE user_custom8List ADD CONSTRAINT FK_6785FD13108B7592 FOREIGN KEY (original_id) REFERENCES user_custom8List (id)');
        $this->addSql('ALTER TABLE user_custom8List ADD CONSTRAINT FK_6785FD1361220EA6 FOREIGN KEY (creator_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom8List ADD CONSTRAINT FK_6785FD13A43E35E8 FOREIGN KEY (updatedby_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom8List ADD CONSTRAINT FK_6785FD13BD42F28C FOREIGN KEY (objectType_id) REFERENCES user_objectTypeList (id)');
        $this->addSql('ALTER TABLE user_custom9List ADD CONSTRAINT FK_5AE5D4A3108B7592 FOREIGN KEY (original_id) REFERENCES user_custom9List (id)');
        $this->addSql('ALTER TABLE user_custom9List ADD CONSTRAINT FK_5AE5D4A361220EA6 FOREIGN KEY (creator_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom9List ADD CONSTRAINT FK_5AE5D4A3A43E35E8 FOREIGN KEY (updatedby_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_custom9List ADD CONSTRAINT FK_5AE5D4A3BD42F28C FOREIGN KEY (objectType_id) REFERENCES user_objectTypeList (id)');
        $this->addSql('ALTER TABLE user_daysList ADD CONSTRAINT FK_AB2E9C55108B7592 FOREIGN KEY (original_id) REFERENCES user_daysList (id)');
        $this->addSql('ALTER TABLE user_daysList ADD CONSTRAINT FK_AB2E9C5561220EA6 FOREIGN KEY (creator_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_daysList ADD CONSTRAINT FK_AB2E9C55A43E35E8 FOREIGN KEY (updatedby_id) REFERENCES user_fosuser (id)');
        $this->addSql('ALTER TABLE user_daysList ADD CONSTRAINT FK_AB2E9C55BD42F28C FOREIGN KEY (objectType_id) REFERENCES user_objectTypeList (id)');
    }
}
