<?php

namespace Oleg\OrderformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatusGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusGroupRepository extends EntityRepository
{
}
